#  Copyright (c) Brockmann Consult GmbH, 2025
#  License: MIT
name: kaleidoscope-mini
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  # Imports
  - dask
  - dask-image
  - numpy
  - xarray
  # Runtime
  - h5netcdf
