#  Copyright (c) Brockmann Consult GmbH, 2025
#  License: MIT

## The default source type.
source_type: _

## Detect the reader engine automatically
engine_reader:

## Detect the writer engine automatically
engine_writer:

## The default log level ["error", "warning", "info", "debug", "off"]
log_level: "info"

## The default mode ["multithreading", "synchronous"]
mode: "multithreading"

## The number of workers
workers: 2

## Disable progress bar display.
progress: False

## Disable stack traces.
stack_traces: False

## Use the working directory for temporary files.
tmpdir: "."
